### PR TITLE
Vca test

### PR DESCRIPTION
**Pull request by tarunmangla**
@ggmartins can you please take a look at the code and see if the changes make sense

### CODE REVIEW

**Review by ggmartins — CHANGES_REQUESTED** [review]
if you can rebase with the latest, reimplement as a plugin and resubmit, that would be awesome, because right now it raising an conflict alert

**Comment by tarunmangla** [comment]
modified the netrics integration. @ggmartins can you check now?

**Review by ggmartins — CHANGES_REQUESTED** [review]
could you please remove:
package/deb/nm-exp-active-netrics/* (including nm-exp-active-netrics)
and the .deb package?
thanks

**Comment by tarunmangla** [comment]
> could you please remove: package/deb/nm-exp-active-netrics/* (including nm-exp-active-netrics) and the .deb package? thanks

shall i add it to gitignore?

**Comment by ggmartins** [comment]
yeah, that works

**Comment by tarunmangla** [comment]
> yeah, that works

check now

**Review by ggmartins — APPROVED** [review]
Done.

**Pull request merged**
